// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


void ui_event_comp_wifiSelect_wifiSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_wifiSelect = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// COMPONENT wifiSelect

lv_obj_t * ui_wifiSelect_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_wifiSelect;
    cui_wifiSelect = lv_dropdown_create(comp_parent);
    lv_dropdown_set_options(cui_wifiSelect, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(cui_wifiSelect, 223);
    lv_obj_set_height(cui_wifiSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_wifiSelect, -36);
    lv_obj_set_y(cui_wifiSelect, -97);
    lv_obj_set_align(cui_wifiSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_wifiSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_WIFISELECT_NUM);
    children[UI_COMP_WIFISELECT_WIFISELECT] = cui_wifiSelect;
    lv_obj_add_event_cb(cui_wifiSelect, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_wifiSelect, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_wifiSelect, ui_event_comp_wifiSelect_wifiSelect, LV_EVENT_ALL, children);
    ui_comp_wifiSelect_create_hook(cui_wifiSelect);
    return cui_wifiSelect;
}

