// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_WIFISELECT_H
#define _UI_COMP_WIFISELECT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT wifiSelect
#define UI_COMP_WIFISELECT_WIFISELECT 0
#define _UI_COMP_WIFISELECT_NUM 1
lv_obj_t * ui_wifiSelect_create(lv_obj_t * comp_parent);
void ui_event_comp_wifiSelect_wifiSelect(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
